use std::fs;
use std::io::Write;

use serde_core::Serialize;
use serde_json::ser::PrettyFormatter;
use serde_json::{Serializer, Value, json};
use update_api_list::{Crate, CrateDefinitions, WORKSPACE_ROOT};

fn main() {
    // let defs = CrateDefinitions::new();

    let mut list = vec!["# autogenerated by update-api-list"];
    let map = json! {{
        "__comment0": "Autogenerated by update-api-list.",
        "__comment1": "List of files that define a function with a given name, used in \
                       CI. This file is checked in to make it obvious if refactoring breaks \
                       things."
    }};

    let libm_defs = update_api_list::new::crate_function(Crate::Libm);

    // TODO
    fs::write(
        WORKSPACE_ROOT.join("etc/deleteme.txt"),
        &format!("{libm_defs:#?}"),
    )
    .unwrap();

    // let Value::Object(mut map) = map else {
    //     unreachable!()
    // };

    // for def in defs.functions.values() {
    //     if !def.should_test.get() {
    //         continue;
    //     }

    //     let value = json! {{
    //         // "type": def.root_type.name(),
    //         "sources": def.sources.borrow().clone(),
    //     }};

    //     assert!(
    //         !list.contains(&def.name.as_str()),
    //         "duplicate function found: {def:#?}"
    //     );

    //     map.insert(def.name.clone(), value);
    //     list.push(&def.name);
    // }

    // map.sort_keys();
    // list.sort_unstable();

    // let mut buf = Vec::new();
    // let pretty = PrettyFormatter::with_indent(b"    ");
    // let mut ser = Serializer::with_formatter(&mut buf, pretty);
    // map.serialize(&mut ser).unwrap();

    // fs::write(
    //     WORKSPACE_ROOT.join("etc/deleteme.txt"),
    //     &format!("{defs:#?}"),
    // )
    // .unwrap();
    // fs::write(WORKSPACE_ROOT.join("etc/function-definitions2.json"), &buf).unwrap();

    // buf.clear();

    // for name in list {
    //     writeln!(buf, "{name}").unwrap();
    // }

    // fs::write(WORKSPACE_ROOT.join("etc/function-list2.txt"), &buf).unwrap();
}
